package lbi.usp.br.caravela.img;

public enum IMGFileFieldIndex {
	
	GENE_ID_LOCATION,
	TYPE_ID_LOCATION,
	IDENTITY_LOCATION,
	ALIGN_LENGTH_LOCATION,
	QUERY_START_LOCATION,
	QUERY_END_LOCATION,
	SUBJECT_START_LOCATION,
	SUBJECT_END_LOCATION,
	EVALUE_LOCATION,
	BIT_SCORE_LOCATION;
}
